"""Regulation-specific margin calculators."""

from margin_calc_engine.calculators.reg_t import RegTCalculator
from margin_calc_engine.calculators.finra_4210 import FINRA4210Calculator
from margin_calc_engine.calculators.strategy_margin import StrategyMarginCalculator
from margin_calc_engine.calculators.strategy_recognizer import StrategyRecognizer
from margin_calc_engine.calculators.portfolio_margin import PortfolioMarginCalculator
from margin_calc_engine.calculators.concentrated import ConcentratedAccountCalculator
from margin_calc_engine.calculators.day_trading import DayTradeDetector
from margin_calc_engine.calculators.sma import SMACalculator
