"""Regulation-specific margin calculators."""

from paragraph_margin.calculators.reg_t import RegTCalculator
from paragraph_margin.calculators.finra_4210 import FINRA4210Calculator
from paragraph_margin.calculators.strategy_margin import StrategyMarginCalculator
from paragraph_margin.calculators.strategy_recognizer import StrategyRecognizer
from paragraph_margin.calculators.portfolio_margin import PortfolioMarginCalculator
from paragraph_margin.calculators.concentrated import ConcentratedAccountCalculator
from paragraph_margin.calculators.day_trading import DayTradeDetector
from paragraph_margin.calculators.sma import SMACalculator
